### ISSUE TITLE
Logo for the "Griddle & Github Grill"

### ISSUE THREAD

**Issue by goldilocks0164** [chingu-voyages/v50-tier1-team-03#57]
*
** As a restaurant customer, I would like the restaurant webpage to clearly display the title and logo on the Header, so that I want to immediately recognize the restaurant's brand and understand its purpose.

**Acceptance Criteria:**

The restaurant's logo is prominently displayed in the header. The logo should be high-resolution and visually appealing.

The restaurant's name is displayed clearly next to or below the logo. The font should be easy to read and consistent with the overall brand.

Please find attached "Griddle & Github Logo"

![Image](https://github.com/user-attachments/assets/4f0abd93-84fc-43ae-aca7-04bbee969b48)

**Comment by Mikelovin23** [comment]
As per comments made in the discord, the spelling is incorrect for the word GRIDDLE.
There also seems to be a strange shape fill (see attached close up)


![Image](https://github.com/user-attachments/assets/e8a02b5c-c18a-4a98-bf9c-4216603af968)

**Comment by goldilocks0164** [comment]
![Image](https://github.com/user-attachments/assets/f2dcf35d-b065-4623-a3a0-ce06928f6425)

Few more images

**Comment by goldilocks0164** [comment]
As per the discussion we had, since Adrienne is the UI/UX designer, she is in charge of the logo. I will go ahead and delete the above two images.

**Comment by Adrienne-B** [comment]
Hello everyone, I am developing our first logo option based on a discussion I had with our product owner. I plan to create 3-4 different logos for everyone to review and provide input on. Thank you for your collaboration.
